-- GENERATED by scripts/ossie_bridge.py from osi/court_usage.json — do not edit.
-- Change the Ossie document and rerun: uv run scripts/ossie_bridge.py import

SELECT
    *,
    court_number || '-' || reservation_date || '-' || start_time AS slot_id
FROM {{ ref('fct_hourly_usage') }}
