# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "apache-ossie-dbt @ git+https://github.com/apache/ossie.git@938a439f0170abfe702952f6871f2221690becb5#subdirectory=converters/dbt",
#   "pyyaml>=6.0",
# ]
# ///
"""
Bridge between Apache Ossie documents and a dbt v2 (Fusion) project.

dbt v1.12 reads Ossie documents from osi/ natively; dbt v2 does not. This
script closes the gap using the official Apache Ossie dbt converter:

  import   osi/*.json  ->  models/metrics/ossie/  (a dbt model + latest-spec YAML)
  export   target/semantic_manifest.json  ->  target/ossie_document.yaml

Run from the project root with uv (no install step needed):

  uv run scripts/ossie_bridge.py import
  uv run scripts/ossie_bridge.py export

Import conventions:
  * A dataset's `source` is database.schema.alias. Only the alias is used, and
    it must be a dbt model name; the generated model refs it, so the same Ossie
    document works in dev and prod.
  * Fields with a computed expression become columns on the generated model.
  * Ossie has no aggregation time dimension. It is taken from a DBT custom
    extension on the dataset ({"agg_time_dimension": "..."}), or else from the
    dataset's only time field.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml
from metricflow_semantic_interfaces.type_enums import DimensionType, EntityType, MetricType
from metricflow_semantics.model.dbt_manifest_parser import parse_manifest_from_dbt_generated_manifest
from ossie import OssieDocument
from ossie_dbt import MSIToOssieConverter, OssieToMSIConverter

OSSIE_DIR = Path("osi")
OUTPUT_DIR = Path("models/metrics/ossie")
HEADER = (
    "# GENERATED by scripts/ossie_bridge.py from {src} — do not edit.\n"
    "# Change the Ossie document and rerun: uv run scripts/ossie_bridge.py import\n"
)


def load_documents(path: Path) -> list[OssieDocument]:
    """Read an Ossie file. Accepts the released 0.1.x shape (a `semantic_model`
    array) as well as the flat 0.2 shape the converter expects."""
    raw = json.loads(path.read_text()) if path.suffix == ".json" else yaml.safe_load(path.read_text())
    models = raw["semantic_model"] if "semantic_model" in raw else [raw]
    return [OssieDocument.model_validate({**m, "version": "0.2.0.dev0"}) for m in models]


def dbt_extension(dataset) -> dict:
    for ext in dataset.custom_extensions or []:
        if ext.vendor_name.upper() == "DBT":
            return json.loads(ext.data)
    return {}


def import_documents() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in sorted(OSSIE_DIR.glob("**/*")):
        if path.suffix not in {".json", ".yml", ".yaml"}:
            continue
        for doc in load_documents(path):
            result = OssieToMSIConverter().convert(doc)
            for issue in result.issues:
                print(f"[warning] {path}: {issue.issue_type.value}: {issue.element_name}", file=sys.stderr)
            manifest = result.output
            ossie_datasets = {d.name: d for d in doc.datasets}
            for sm in manifest.semantic_models:
                metrics = [m for m in manifest.metrics if owning_model(m) == sm.name]
                ratios = [m for m in manifest.metrics if m.type is MetricType.RATIO and uses(m, metrics)]
                write_model(path, sm, ossie_datasets[sm.name], metrics, ratios)


def owning_model(metric) -> str | None:
    params = metric.type_params.metric_aggregation_params
    return params.semantic_model if params else None


def uses(ratio, simple_metrics) -> bool:
    names = {m.name for m in simple_metrics}
    return ratio.type_params.numerator.name in names


def write_model(src: Path, sm, dataset, simple_metrics, ratio_metrics) -> None:
    model_name = f"ossie_{sm.name}"
    upstream = sm.node_relation.alias
    fields = {f.name: f for f in dataset.fields or []}

    # Computed Ossie fields become real columns, so every entity and dimension
    # below maps onto a column of the generated model.
    computed = [(e.name, e.expr) for e in [*sm.entities, *sm.dimensions] if e.expr]
    select = ",\n".join(["    *", *[f"    {expr} AS {name}" for name, expr in computed]])
    (OUTPUT_DIR / f"{model_name}.sql").write_text(
        HEADER.replace("# ", "-- ").format(src=src)
        + f"\nSELECT\n{select}\nFROM {{{{ ref('{upstream}') }}}}\n"
    )

    time_dims = [d.name for d in sm.dimensions if d.type is DimensionType.TIME]
    agg_time = dbt_extension(dataset).get("agg_time_dimension")
    if agg_time is None:
        if len(time_dims) != 1:
            sys.exit(
                f"{src}: dataset '{sm.name}' has {len(time_dims)} time fields; add a DBT custom "
                'extension {"agg_time_dimension": "<field>"} to pick one.'
            )
        agg_time = time_dims[0]

    columns = []
    for e in sm.entities:
        columns.append({
            "name": e.name,
            "description": e.description,
            "entity": {"type": EntityType(e.type).value, "name": e.name},
        })
    for d in sm.dimensions:
        column = {"name": d.name, "description": d.description}
        if d.type is DimensionType.TIME:
            column["granularity"] = d.type_params.time_granularity.value
        column["dimension"] = {"type": d.type.value, "label": d.label or fields[d.name].label}
        columns.append(column)

    metrics = []
    for m in simple_metrics:
        params = m.type_params.metric_aggregation_params
        metrics.append({
            "name": metric_name(m.name),
            "label": label(m.name),
            "description": m.description,
            "type": "simple",
            "agg": params.agg.value,
            "expr": m.type_params.expr,
        })

    body = {
        "models": [{
            "name": model_name,
            "description": dataset.description,
            "semantic_model": {"enabled": True, "name": sm.name},
            "agg_time_dimension": agg_time,
            "columns": [strip_none(c) for c in columns],
            "metrics": [strip_none(m) for m in metrics],
        }],
    }
    if ratio_metrics:
        body["metrics"] = [strip_none({
            "name": m.name,
            "label": label(m.name),
            "description": m.description,
            "type": "ratio",
            "numerator": metric_name(m.type_params.numerator.name),
            "denominator": metric_name(m.type_params.denominator.name),
        }) for m in ratio_metrics]

    out = OUTPUT_DIR / f"_{model_name}.yml"
    out.write_text(HEADER.format(src=src) + "\n" + yaml.safe_dump(body, sort_keys=False, width=100, allow_unicode=True))
    print(f"{src} -> {OUTPUT_DIR / model_name}.sql, {out}")


def metric_name(name: str) -> str:
    # The converter names ratio inputs `<ratio>__numerator`; dbt forbids "__" in names.
    return name.replace("__", "_")


def label(name: str) -> str:
    return " ".join(part for part in name.split("_") if part).capitalize()


def strip_none(d: dict) -> dict:
    return {k: (strip_none(v) if isinstance(v, dict) else v) for k, v in d.items() if v is not None}


def export_manifest(manifest_path: Path, output: Path, model_name: str) -> None:
    manifest = parse_manifest_from_dbt_generated_manifest(manifest_path.read_text())
    result = MSIToOssieConverter().convert(manifest, ossie_model_name=model_name)
    for issue in result.issues:
        print(f"[warning] {issue.issue_type.value}: {issue.element_name}", file=sys.stderr)
    output.write_text(result.output.to_ossie_yaml())
    print(f"{manifest_path} -> {output}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("import", help="osi/ -> dbt models + YAML in models/metrics/ossie/")
    export = sub.add_parser("export", help="target/semantic_manifest.json -> Ossie YAML")
    export.add_argument("-i", "--input", type=Path, default=Path("target/semantic_manifest.json"))
    export.add_argument("-o", "--output", type=Path, default=Path("target/ossie_document.yaml"))
    export.add_argument("--model-name", default="ztc_analytics")
    args = parser.parse_args()

    if args.command == "import":
        import_documents()
    else:
        export_manifest(args.input, args.output, args.model_name)


if __name__ == "__main__":
    main()
